In [ ]:
import numpy as np

3. Seleziona il numero più vicino a 0.5 in un array casuale

Genera un array 10 x 3 con numeri casuali nell'intervallo [0,1]. Per ogni riga, seleziona il numero più vicino a 0.5. Per farlo usa il fancy indexing.

In [ ]:
m = np.random.rand(10, 3)
print(f"Matrice: \n {m}\n")

print(f"Numeri vicino a 0.5: \n{m[np.isclose(m, 0.5, rtol=1e-1)]}")


Matrice: 
 [[0.91434676 0.76405531 0.94705529]
 [0.32722801 0.92749219 0.1010625 ]
 [0.83800746 0.24978364 0.43638317]
 [0.7209737  0.69086373 0.50350168]
 [0.24206404 0.35199172 0.37002359]
 [0.35567221 0.26859041 0.6746655 ]
 [0.50189079 0.7892225  0.16690849]
 [0.50242863 0.27676445 0.57948648]
 [0.21045026 0.22689667 0.74145004]
 [0.00846487 0.62767455 0.95108094]]

Numeri vicino a 0.5: 
[0.50350168 0.50189079 0.50242863]
