In [2]:
import numpy as np

2. Operazioni su array

Crea un array a, 2D (senza digitarlo esplicitamente), e genera due nuovi array b, contenente la sua 2ª e 4ª riga, e c contenente solo la 3ª. Dividi ogni colonna dell'array a, elemento per elemento, con l'array c.

In [3]:
a = np.arange(20).reshape((4, 5))

print(f"Matrice:\n {a}\n")

#seconda e quarta riga
b = a[[1,3]]

print(f"Seconda e Quarta riga:\n {b}\n")

#terza riga
c = a[2]

print(f"Terza riga: \n{c}\n")

#divisione
print(f"Divisione\n {a/c}")



Matrice:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Seconda e Quarta riga:
 [[ 5  6  7  8  9]
 [15 16 17 18 19]]

Terza riga: 
[10 11 12 13 14]

Divisione
 [[0.         0.09090909 0.16666667 0.23076923 0.28571429]
 [0.5        0.54545455 0.58333333 0.61538462 0.64285714]
 [1.         1.         1.         1.         1.        ]
 [1.5        1.45454545 1.41666667 1.38461538 1.35714286]]
