In [2]:
import numpy as np

7. Analisi di una matrice

Data la matrice survey con età, reddito e anni di istruzione


In [4]:
survey_matrix = np.array([ [25, 40000, 10], [32, 52000, 12], [40, 63000, 14], [29, 47000, 11], [35, 58000, 13] ])

print(survey_matrix)

[[   25 40000    10]
 [   32 52000    12]
 [   40 63000    14]
 [   29 47000    11]
 [   35 58000    13]]


7.1 Seleziona dalla matrice solo gli intervistati con almeno 12 anni di istruzione utilizzando un test logico.

In [9]:
print(survey_matrix[survey_matrix[:,2] >= 12])

[[   32 52000    12]
 [   40 63000    14]
 [   35 58000    13]]


7.2 In un'unica riga di codice, seleziona i redditi degli intervistati con almeno 12 anni di istruzione.



In [11]:
print(survey_matrix[survey_matrix[:,2] >= 12][:,1])

[52000 63000 58000]


7.3 In un'unica riga di codice, calcola il reddito medio degli intervistati con almeno 12 anni di istruzione.

In [12]:
print(sum(survey_matrix[survey_matrix[:,2] >= 12][:,1])/len(survey_matrix[survey_matrix[:,2] >= 12][:,1]))

57666.666666666664
